name: Rockchip OpenWrt Build

on:
  repository_dispatch:
  workflow_dispatch:

env:
  OPNAME: 'R68S、R2S、R4S、R5C、R5S、OPiR1Plus'
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  EXTERNAL_FILE: configs/luci/Standard.config
  CONFIG_FILE: configs/Rockchip.config
  SYS_CONF_SH: configure.sh
  PACKS: package.sh
  EXTEND_DRIVER: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* 
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://raw.githubusercontent.com/bigbugcc/openwrts/master/openwrt-env)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /mnt/workdir
        sudo chown $USER:$GROUPS /mnt/workdir

    - name: Clone source code
      working-directory: /mnt/workdir
      run: |
        git clone --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        ln -sf /mnt/workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Cache
      uses: stupidloud/cachewrtbuild@main
      with:
          ccache: 'true'
          mixkey: 'armv8'
          prefix: 'openwrt'

    # ------------------------------
    # Update and install feeds first
    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    # Load custom feeds
    - name: Load custom feeds
      run: |
        cd openwrt
        [ -e $GITHUB_WORKSPACE/$FEEDS_CONF ] && mv $GITHUB_WORKSPACE/$FEEDS_CONF feeds.conf.default
        chmod +x $GITHUB_WORKSPACE/$SYS_CONF_SH
        bash $GITHUB_WORKSPACE/$SYS_CONF_SH

    # Load custom configuration and package
    - name: Load custom configuration
      run: |
        cd openwrt
        [ -e $GITHUB_WORKSPACE/files ] && mv $GITHUB_WORKSPACE/files files
        [ -e $GITHUB_WORKSPACE/$CONFIG_FILE ] && mv $GITHUB_WORKSPACE/$CONFIG_FILE .config
        chmod +x $GITHUB_WORKSPACE/$PACKS
        bash $GITHUB_WORKSPACE/$PACKS

    # Extend Driver
    - name: Extend Driver
      if: env.EXTEND_DRIVER == 'true'
      run: |
        cd openwrt
        cat $GITHUB_WORKSPACE/configs/Driver.config >> .config

    # Modify configuration
    - name: Modify configuration
      run: |
        cd openwrt
        cat $GITHUB_WORKSPACE/$EXTERNAL_FILE >> .config
        make defconfig
        sed -i '/CONFIG_DEFAULT_luci/d' .config
        cat .config

    # Download packages
    - name: Download packages
      run: |
        cd openwrt
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    # Compile firmware
    - name: Compile firmware
      id: compile
      run: |
        cd openwrt
        echo "$(nproc) thread compile"
        make -j$(nproc) V=s || make -j4 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=R2S-R4S-OPiR1Plus" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    # Upload bin directory
    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    # Organize firmware files
    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    # Upload firmware
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    # Release tag
    - name: Generate release tag
      id: tag
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Generate release body
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ steps.tag.outputs.release_tag }}/total?style=flat-square)" >> release.txt
        echo "- FastRhino R68S" >> release.txt
        echo "- FriendlyARM NanoPi R2S | R4S | R5C | R5S " >> release.txt
        echo "- Xunlong Orange Pi R1 Plus" >> release.txt

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.OPNAME }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
